# -*- coding: utf-8 -*-
"""desafio_colab_flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcKKkBlbGtqVXitpoqaBa-07M03XTOkl
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk

app = Flask(__name__)
run_with_ngrok(app)

d = {
    "name": "Nikola",
    "surname": "Tesla",
    "age": 60
}

@app.route('/')

def home():
  return "Saída gerada"

@app.route('/input')

def input():
  return jsonify(d)

@app.route('/output', methods=['GET, POST'])

def predJson():
  pred = rk.choice(['positive','negative'])
  nd = d
  nd['prediction']=pred
  return jsonify(nd)

app.run()